version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'eslint'
        versions: ['9.x']
      - dependency-name: 'eslint-plugin-cypress'
        versions: ['4.x', '5.x']
      - dependency-name: '@angular/*'
        versions: ['18.x', '19.x', '20.x']
      - dependency-name: '@angular-devkit/build-angular'
        versions: ['18.x', '19.x', '20.x']
      - dependency-name: '@angular-eslint/*'
        versions: ['18.x', '19.x', '20.x']
      - dependency-name: 'ng-packagr'
        versions: ['18.x', '19.x', '20.x']
      - dependency-name: 'typescript'
        versions: ['5.5.x', '5.6.x', '5.7.x', '5.8.x', '5.9.x']
      - dependency-name: 'zone'
        versions: ['0.15.x']
