version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'eslint'
        # Angular@17 is not compatible with eslint flat config
        versions: ['>=9.0.0']
      - dependency-name: '@angular/*'
        # This is an angular@17 project
        versions: ['>=18.0.0']
      - dependency-name: '@angular-devkit/build-angular'
        versions: ['>=18.0.0']
      - dependency-name: '@angular-eslint/*'
        versions: ['>=18.0.0']
      - dependency-name: 'ng-packagr'
        versions: ['>=18.0.0']
      - dependency-name: 'typescript'
        # Angular@17.3 requires typescript >=5.2.0 <5.5.0
        versions: ['>=5.5.0']
      - dependency-name: 'zone.js'
        # Angular@17.3 requires zone 0.14.x
        versions: ['>=0.15.0']
      - dependency-name: 'jasmine-core'
        # jasmine-core@7 ff. is not compatible with zone and karma required by angular@17
        versions: ['>=7.0.0']
      - dependency-name: 'cypress'
        # Cypress@15 ff. requires webpack@4 that is not compatible with angular@17
        versions: ['>=15.0.0']
      - dependency-name: '@cypress/schematic'
        versions: ['>=4.0.0']
      - dependency-name: '@cypress/webpack-preprocessor'
        versions: ['>=7.0.0']
      - dependency-name: 'eslint-plugin-cypress'
        versions: ['>=4.0.0']
      - dependency-name: '@types/node'
        # @types/node@25 ff. break the tests
        versions: ['>=25.0.0']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
