name: publish-src-to-github-pages

on:
  push:
    branches: ['main']

  workflow_dispatch:

    # Ensure only one deployment runs at a time.
# We set 'cancel-in-progress: false' to let active deployments finish safely before starting a new one.
concurrency:
  group: 'pages'
  cancel-in-progress: false

env:
  # Avoid installing Git Hooks
  HUSKY: 0

jobs:
  # Build job
  build:
    permissions:
      contents: write

    runs-on: ubuntu-24.04

    steps:
      - name: Check out
        uses: actions/checkout@v7.0.1

      - name: Use Node V24
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build:ghpages

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          name: github-pages
          path: ghpages/

  # Deployment job
  deploy:
    needs: build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-24.04

    # Uses following settings for Github Pages:
    #   Build and deployment > Source: GithubAction (with publish-src-to-github-pages workflow)
    # and for Environments "github-pages":
    #   Deployment branches and tags > "main"
    steps:
      - name: Publish current web page to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.1
        with:
          artifact_name: github-pages
